spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: 101.133.165.3:9092
    consumer:
      group-id: user-service
  cloud:
    bus:
      enabled: true
  datasource:
    url: jdbc:mysql://101.133.165.3:3306/gper_mall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: refresh,hystrix.stream

mybatis:
  type-aliases-package: com.gupaoedu.example.userserviceprovider.mapper.entitys